sudo: false
language: python
python:
- '3.6'
env:
- DJANGO_VERSION=2.1.1
before_script:
- pip install -e .
- pip install pycodestyle
- pip install coverage
- pip install python-coveralls
- npm install -g jshint
- cp travis-ci/manage.py manage.py
script:
- pycodestyle supporttools/
- jshint supporttools/static/supporttools/js/ --verbose
- python -m compileall supporttools/
- coverage run --source=supporttools manage.py test supporttools
after_script:
- coveralls
before_deploy:
- find supporttools/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > supporttools/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: QSvfDjMYBNr5zZdek6k4Z+ePBg4JPEbdXEXMZzefGlvevSvrNDgjt5DzjFa+P7HkyNSH1BeeYjyGGqxY0F1GZ1s2629dHl9CT33gG0nd9iWgQ6yJe7lC6LYjJz8YAl5xJCY2as8LwclbL5OalesAXx2/djs5wL268gCU+Lm9h9A=
  on:
    tags: true
    python: '3.6'
