language: python
python:
  - "2.7"
  - "2.6"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6* ]]; then pip install -r travis-2.6-requirements.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7* ]]; then pip install -r requirements.txt; fi
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
script:
  - pep8 --exclude=migrations supporttools
  - coverage run --source=supporttools manage.py test supporttools
after_script:
  - coveralls
notifications:
  email: false
  webhooks:
      urls:
        - https://yarn.cac.washington.edu/rest/botalyst/v1/travis-ci