sudo: false
language: python
python:
  - "3.4"
  - "2.7"
install: pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - cp travis-ci/manage.py manage.py
script:
  - pep8 --exclude=migrations supporttools
  - coverage run --source=supporttools manage.py test supporttools
after_script:
  - coveralls
notifications:
  email: false
